Add OTEL Metrics
nats-io/nats.net pull request #629
Opened 2024-09-13 16:20 UTC by divyeshio

Fixes #316 

- Replaces `NatsStas` functionality to System.Diagnostics.Metrics implementation

2025-01-30 14:27 UTC, iby-dev commented
Any updates on this PR, since? I can see it has been outstanding for a few months now.

2025-02-12 20:55 UTC, iby-dev commented
Hallo, my TL is against aspire so we won't be using it. There is a container that one can use auto extracts metrics from a running nats server which i may have a look at it. I will come back to this depending on how i get on. It is at the bottom of my last sadly.

2025-05-13 17:22 UTC, thompson-tomo requested changes

2025-05-13 17:22 UTC, thompson-tomo commented on src/NATS.Client.Core/Internal/NatsMetrics.cs
> +    public const string SentMessagesInstrumentName = $"{InstrumentPrefix}.sent.messages";
Should be `messaging.client.sent.messages` as per https://opentelemetry.io/docs/specs/semconv/messaging/messaging-metrics/#metric-messagingclientsentmessages

2025-05-13 17:22 UTC, thompson-tomo commented on src/NATS.Client.Core/Internal/NatsMetrics.cs
> +    public const string ReceivedMessagesInstrumentName = $"{InstrumentPrefix}.received.messages";
Should be `messaging.client.consumed.messages` as per https://opentelemetry.io/docs/specs/semconv/messaging/messaging-metrics/#metric-messagingclientconsumedmessages

2025-05-13 17:22 UTC, thompson-tomo commented on src/NATS.Client.Core/Internal/NatsMetrics.cs
> +    public const string PendingMessagesInstrumentName = $"{InstrumentPrefix}.pending.messages";
Suggest a request is raised to add this

2025-05-13 17:22 UTC, thompson-tomo commented on src/NATS.Client.Core/Internal/NatsMetrics.cs
> +    public const string ReceivedBytesInstrumentName = $"{InstrumentPrefix}.received.bytes";
Suggest raising a request to add these to registry just like we have in http https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestbodysize

2025-05-13 17:22 UTC, thompson-tomo commented on src/NATS.Client.Core/Internal/NatsMetrics.cs
> +    static NatsMetrics()
Attributes for metrics are missing as per https://opentelemetry.io/docs/specs/semconv/messaging/messaging-metrics/#common-metrics

2025-05-13 17:22 UTC, thompson-tomo commented on src/NATS.Client.Core/Internal/NatsMetrics.cs
> +public class NatsMetrics
Required metrics ie duration is missing as per https://opentelemetry.io/docs/specs/semconv/messaging/messaging-metrics/#common-metrics

2025-05-13 17:22 UTC, thompson-tomo commented on src/NATS.Client.Core/Internal/NatsMetrics.cs
> +public class NatsMetrics
A request needs to be raised to register the system name.

2025-05-14 04:30 UTC, thompson-tomo commented on src/NATS.Client.Core/Internal/NatsMetrics.cs
> +    public const string ReceivedBytesInstrumentName = $"{InstrumentPrefix}.received.bytes";
Raised as https://github.com/open-telemetry/semantic-conventions/issues/2264

2025-05-16 13:49 UTC, mtmk commented
thanks for the comments @thompson-tomo. we might have to open a new pr not sure if @divyeshio is still interested in this feature. been a while.

2025-05-22 06:49 UTC, divyeshio commented
Hey @mtmk @thompson-tomo, sorry I've been inactive, I won't be able to work on this.

2025-05-22 09:36 UTC, mtmk commented
> Hey @mtmk @thompson-tomo, sorry I've been inactive, I won't be able to work on this.

thanks for the update @divyeshio 💯 thank you for kicking this off and your hard work ❤️

2025-05-24 11:30 UTC, thompson-tomo commented
@mtmk I have now created #871 which contains functionality from this PR plus some fixes. As such I think this one can be closed.

2025-05-24 11:34 UTC, mtmk commented
Thank you @thompson-tomo

2025-05-24 11:34 UTC, closed without merging

2025-11-13 16:21 UTC, sardmhmd approved these changes